src/Entity/Channel.php
<?php

namespace App\Entity;

use App\Repository\ChannelRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ChannelRepository::class)
 */
class Channel
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $num;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $creation_date;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $language;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNum(): ?int
    {
        return $this->num;
    }

    public function setNum(int $num): self
    {
        $this->num = $num;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creation_date;
    }

    public function setCreationDate(\DateTimeInterface $creation_date): self
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    public function getLanguage(): ?string
    {
        return $this->language;
    }

    public function setLanguage(?string $language): self
    {
        $this->language = $language;

        return $this;
    }
}

src/Form/ChannelType.php
<?php

namespace App\Form;

use App\Entity\Channel;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ChannelType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('num')
            ->add('name')
            ->add('creation_date')
            ->add('language')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Channel::class,
        ]);
    }
}

src/Controller/ChannelController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/channel")
 */
class ChannelController extends AbstractController
{
    /**
     * @Route("/", name="channel_index", methods={"GET"})
     */
    public function index(): Response
    {
        return $this->render('channel/index.html.twig', [
            'controller_name' => 'ChannelController'
        ]);
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("/home", name="home")
     */
    public function index(): Response
    {
        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            {#{{ encore_entry_link_tags('app') }}#}
        {% endblock %}

        {% block javascripts %}
            {#{{ encore_entry_script_tags('app') }}#}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/channel/_delete_form.html.twig
<form method="post" action="{{ path('channel_delete', {'id': channel.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ channel.id) }}">
    <button class="btn">Delete</button>
</form>

templates/channel/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/channel/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Channel{% endblock %}

{% block body %}
    <h1>Edit Channel</h1>

    {{ include('channel/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('channel_index') }}">back to list</a>

    {{ include('channel/_delete_form.html.twig') }}
{% endblock %}

templates/channel/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Channel index{% endblock %}

{% block body %}
    <h1>Channel index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Num</th>
                <th>Name</th>
                <th>Language</th>
                <th>Creation date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for channel in channels %}
            <tr>
                <td>{{ channel.id }}</td>
                <td>{{ channel.num }}</td>
                <td>{{ channel.name }}</td>
                <td>{{ channel.language }}</td>
                <td>{{ channel.creationDate ? channel.creationDate|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('channel_show', {'id': channel.id}) }}">show</a>
                    <a href="{{ path('channel_edit', {'id': channel.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('channel_new') }}">Create new</a>
{% endblock %}

templates/channel/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Channel{% endblock %}

{% block body %}
    <h1>Create new Channel</h1>

    {{ include('channel/_form.html.twig') }}

    <a href="{{ path('channel_index') }}">back to list</a>
{% endblock %}

templates/channel/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Channel{% endblock %}

{% block body %}
    <h1>Channel</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ channel.id }}</td>
            </tr>
            <tr>
                <th>Num</th>
                <td>{{ channel.num }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ channel.name }}</td>
            </tr>
            <tr>
                <th>Creation_date</th>
                <td>{{ channel.creationDate ? channel.creationDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Language</th>
                <td>{{ channel.language }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('channel_index') }}">back to list</a>

    <a href="{{ path('channel_edit', {'id': channel.id}) }}">edit</a>

    {{ include('channel/_delete_form.html.twig') }}
{% endblock %}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Hello{% endtrans %} {{ controller_name | uppercase }}!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name | uppercase }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/var/www/html/src/Controller/HomeController.php'|file_link(0) }}">src/Controller/HomeController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/var/www/html/templates/home/index.html.twig'|file_link(0) }}">templates/home/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}